### ISSUE TITLE
Review and Approve User Stories

### ISSUE THREAD

**Issue by jkreinb** [mtvis/smarter-university-system-group-1#19]
Activity of #8 

Review user stories and ensure formatting matches requested per assignment. Ensure:

-All user stories are assigned a unique identifier (e.g., numbers 1...n)
-All stories are properly tied to epics.
-All user stories are traceable to requirements provided.

**Comment by cringley** [comment]
@all - user stories are being mocked here - https://docs.google.com/spreadsheets/d/1R86yMyB_Hto2NfYsxpSMAQnZWqmxr0gW/edit#gid=1661379094

**Comment by cringley** [comment]
As of 04.20.2024 - most of the stories have been created. There are some stories in cells 1 - 32 and I created 50 additional stories starting at cell 34. 

By end of day (EOD) today - can we have everyone review the stories that we agree are needed so we can begin to rank them?
